---
- name: fourth.yaml
  hosts: localhost
  tasks:
  - name: install httpd and start it
    yum:
     name: httpd
     state: present
  - name: start httpd    
    service:
     name: httpd
     state: started

