---
- name: change or update password of user in remote client
  hosts: web

  tasks:
    - name: change or update password
      user:
        name: george
        update_password: always
        password: "{{ my_password|password_hash('sha512') }}"
